version: '3.7'

services:
  fe2_reverseproxy:
    image: odin568/fe2_reverseproxy:latest
    container_name: fe2_reverseproxy
    ports:
      - 80:80
      - 443:443
    restart: always
### The defaults. Uncomment to overwrite
#    environment:
#      - CERTBOT_EMAIL=webmaster@ffw-baudenbach.de
#      - STAGING=0
#      - DHPARAM_SIZE=2048
#      - RSA_KEY_SIZE=2048
#      - RENEWAL_INTERVAL=8d
    volumes:
      - ./nginx_secrets:/etc/letsencrypt
