###########
# This is the default configuration bound to the DynDNS domain.
###########

server {
    listen      443 ssl default_server;
    listen [::]:443 ssl default_server;
    http2 on;
    
    server_name haus.ffw-baudenbach.de;
    
    ###########
    # SSL
    ###########
    
    ssl_certificate /etc/letsencrypt/live/haus.ffw-baudenbach.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/haus.ffw-baudenbach.de/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/haus.ffw-baudenbach.de/chain.pem;
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    ###########
    # Hardening
    # generated 2026-06-24, TLSRef Guideline v6.0, nginx 1.31.1, OpenSSL 3.5.6, intermediate config, HSTS, OCSP, gitrev=f17a584
    # https://configurator.tlsref.org/#server=nginx&version=1.31.1&config=intermediate&openssl=3.5.6&hsts&ocsp&guideline=6.0
    ###########

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    
    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ecdh_curve X25519MLKEM768:X25519:prime256v1:secp384r1;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    # see also ssl_session_ticket_key alternative to stateful session cache
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # replace with the IP address of your resolver;
    # async 'resolver' is important for proper operation of OCSP stapling
    resolver 9.9.9.9 149.112.112.112 valid=300s ipv6=off;
    resolver_timeout 5s;

    ###########
    # Routes
    ###########

    # Set global robots.txt and disallow all bots
    location = /robots.txt {
       add_header Content-Type text/plain;
       return 200 "User-agent: *\nDisallow: /\n";
    }

    # Set a static root route
    location = / {
        default_type text/plain;
        charset utf-8;
        return 200 'Du bist ned falsch, oba hier gibt’s nix z seng.';
    }

    ################################################
    # FE2_Documentation
    # Route to GitHub Pages
    ################################################

    location = /documentation {
        return 301 https://ffw-baudenbach.github.io/FE2_Documentation/;
    }

    location ^~ /documentation/ {
        return 301 https://ffw-baudenbach.github.io/FE2_Documentation/;
    }

    ################################################
    # PvOutputVisualization
    # Route to integrate into AMWeb
    ################################################

    location = /pvoutput {
        return 301 /pvoutput/;
    }

    location /pvoutput/ {
        proxy_connect_timeout 30s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        proxy_pass http://192.168.112.200:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /pvoutput;
    }

}
