name: Release
on:
  create:
    branches: [ dev, main ]
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Adapt version
        if: startsWith(github.ref, 'refs/tags/')
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "fe2_reverseproxy:latest"
          replace: "fe2_reverseproxy:${GITHUB_REF#refs/*/}"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            docker-compose.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
